/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BeforeAfterRouteImport } from './routes/before-after'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWindowCleaningRouteImport } from './routes/services.window-cleaning'
import { Route as ServicesWindowCarpetRouteImport } from './routes/services.window-carpet'
import { Route as ServicesVacateCleaningRouteImport } from './routes/services.vacate-cleaning'
import { Route as ServicesSolarPanelCleaningRouteImport } from './routes/services.solar-panel-cleaning'
import { Route as ServicesRubbishRemovalRouteImport } from './routes/services.rubbish-removal'
import { Route as ServicesOutdoorMaintenanceRouteImport } from './routes/services.outdoor-maintenance'
import { Route as ServicesOfficeCleaningRouteImport } from './routes/services.office-cleaning'
import { Route as ServicesNdisDvaRouteImport } from './routes/services.ndis-dva'
import { Route as ServicesLawnGardeningRouteImport } from './routes/services.lawn-gardening'
import { Route as ServicesHouseCleaningRouteImport } from './routes/services.house-cleaning'
import { Route as ServicesHomeCleaningRouteImport } from './routes/services.home-cleaning'
import { Route as ServicesGutterCleaningRouteImport } from './routes/services.gutter-cleaning'
import { Route as ServicesCommercialCleaningRouteImport } from './routes/services.commercial-cleaning'
import { Route as ServicesCarpetUpholsteryRouteImport } from './routes/services.carpet-upholstery'
import { Route as ServicesAirbnbCleaningRouteImport } from './routes/services.airbnb-cleaning'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BeforeAfterRoute = BeforeAfterRouteImport.update({
  id: '/before-after',
  path: '/before-after',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWindowCleaningRoute = ServicesWindowCleaningRouteImport.update({
  id: '/window-cleaning',
  path: '/window-cleaning',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWindowCarpetRoute = ServicesWindowCarpetRouteImport.update({
  id: '/window-carpet',
  path: '/window-carpet',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesVacateCleaningRoute = ServicesVacateCleaningRouteImport.update({
  id: '/vacate-cleaning',
  path: '/vacate-cleaning',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSolarPanelCleaningRoute =
  ServicesSolarPanelCleaningRouteImport.update({
    id: '/solar-panel-cleaning',
    path: '/solar-panel-cleaning',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesRubbishRemovalRoute = ServicesRubbishRemovalRouteImport.update({
  id: '/rubbish-removal',
  path: '/rubbish-removal',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesOutdoorMaintenanceRoute =
  ServicesOutdoorMaintenanceRouteImport.update({
    id: '/outdoor-maintenance',
    path: '/outdoor-maintenance',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesOfficeCleaningRoute = ServicesOfficeCleaningRouteImport.update({
  id: '/office-cleaning',
  path: '/office-cleaning',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesNdisDvaRoute = ServicesNdisDvaRouteImport.update({
  id: '/ndis-dva',
  path: '/ndis-dva',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLawnGardeningRoute = ServicesLawnGardeningRouteImport.update({
  id: '/lawn-gardening',
  path: '/lawn-gardening',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHouseCleaningRoute = ServicesHouseCleaningRouteImport.update({
  id: '/house-cleaning',
  path: '/house-cleaning',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHomeCleaningRoute = ServicesHomeCleaningRouteImport.update({
  id: '/home-cleaning',
  path: '/home-cleaning',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGutterCleaningRoute = ServicesGutterCleaningRouteImport.update({
  id: '/gutter-cleaning',
  path: '/gutter-cleaning',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCommercialCleaningRoute =
  ServicesCommercialCleaningRouteImport.update({
    id: '/commercial-cleaning',
    path: '/commercial-cleaning',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCarpetUpholsteryRoute =
  ServicesCarpetUpholsteryRouteImport.update({
    id: '/carpet-upholstery',
    path: '/carpet-upholstery',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAirbnbCleaningRoute = ServicesAirbnbCleaningRouteImport.update({
  id: '/airbnb-cleaning',
  path: '/airbnb-cleaning',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/before-after': typeof BeforeAfterRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/services/airbnb-cleaning': typeof ServicesAirbnbCleaningRoute
  '/services/carpet-upholstery': typeof ServicesCarpetUpholsteryRoute
  '/services/commercial-cleaning': typeof ServicesCommercialCleaningRoute
  '/services/gutter-cleaning': typeof ServicesGutterCleaningRoute
  '/services/home-cleaning': typeof ServicesHomeCleaningRoute
  '/services/house-cleaning': typeof ServicesHouseCleaningRoute
  '/services/lawn-gardening': typeof ServicesLawnGardeningRoute
  '/services/ndis-dva': typeof ServicesNdisDvaRoute
  '/services/office-cleaning': typeof ServicesOfficeCleaningRoute
  '/services/outdoor-maintenance': typeof ServicesOutdoorMaintenanceRoute
  '/services/rubbish-removal': typeof ServicesRubbishRemovalRoute
  '/services/solar-panel-cleaning': typeof ServicesSolarPanelCleaningRoute
  '/services/vacate-cleaning': typeof ServicesVacateCleaningRoute
  '/services/window-carpet': typeof ServicesWindowCarpetRoute
  '/services/window-cleaning': typeof ServicesWindowCleaningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/before-after': typeof BeforeAfterRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/services/airbnb-cleaning': typeof ServicesAirbnbCleaningRoute
  '/services/carpet-upholstery': typeof ServicesCarpetUpholsteryRoute
  '/services/commercial-cleaning': typeof ServicesCommercialCleaningRoute
  '/services/gutter-cleaning': typeof ServicesGutterCleaningRoute
  '/services/home-cleaning': typeof ServicesHomeCleaningRoute
  '/services/house-cleaning': typeof ServicesHouseCleaningRoute
  '/services/lawn-gardening': typeof ServicesLawnGardeningRoute
  '/services/ndis-dva': typeof ServicesNdisDvaRoute
  '/services/office-cleaning': typeof ServicesOfficeCleaningRoute
  '/services/outdoor-maintenance': typeof ServicesOutdoorMaintenanceRoute
  '/services/rubbish-removal': typeof ServicesRubbishRemovalRoute
  '/services/solar-panel-cleaning': typeof ServicesSolarPanelCleaningRoute
  '/services/vacate-cleaning': typeof ServicesVacateCleaningRoute
  '/services/window-carpet': typeof ServicesWindowCarpetRoute
  '/services/window-cleaning': typeof ServicesWindowCleaningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/before-after': typeof BeforeAfterRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/services/airbnb-cleaning': typeof ServicesAirbnbCleaningRoute
  '/services/carpet-upholstery': typeof ServicesCarpetUpholsteryRoute
  '/services/commercial-cleaning': typeof ServicesCommercialCleaningRoute
  '/services/gutter-cleaning': typeof ServicesGutterCleaningRoute
  '/services/home-cleaning': typeof ServicesHomeCleaningRoute
  '/services/house-cleaning': typeof ServicesHouseCleaningRoute
  '/services/lawn-gardening': typeof ServicesLawnGardeningRoute
  '/services/ndis-dva': typeof ServicesNdisDvaRoute
  '/services/office-cleaning': typeof ServicesOfficeCleaningRoute
  '/services/outdoor-maintenance': typeof ServicesOutdoorMaintenanceRoute
  '/services/rubbish-removal': typeof ServicesRubbishRemovalRoute
  '/services/solar-panel-cleaning': typeof ServicesSolarPanelCleaningRoute
  '/services/vacate-cleaning': typeof ServicesVacateCleaningRoute
  '/services/window-carpet': typeof ServicesWindowCarpetRoute
  '/services/window-cleaning': typeof ServicesWindowCleaningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/before-after'
    | '/blog'
    | '/contact'
    | '/services'
    | '/blog/$slug'
    | '/services/airbnb-cleaning'
    | '/services/carpet-upholstery'
    | '/services/commercial-cleaning'
    | '/services/gutter-cleaning'
    | '/services/home-cleaning'
    | '/services/house-cleaning'
    | '/services/lawn-gardening'
    | '/services/ndis-dva'
    | '/services/office-cleaning'
    | '/services/outdoor-maintenance'
    | '/services/rubbish-removal'
    | '/services/solar-panel-cleaning'
    | '/services/vacate-cleaning'
    | '/services/window-carpet'
    | '/services/window-cleaning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/before-after'
    | '/blog'
    | '/contact'
    | '/services'
    | '/blog/$slug'
    | '/services/airbnb-cleaning'
    | '/services/carpet-upholstery'
    | '/services/commercial-cleaning'
    | '/services/gutter-cleaning'
    | '/services/home-cleaning'
    | '/services/house-cleaning'
    | '/services/lawn-gardening'
    | '/services/ndis-dva'
    | '/services/office-cleaning'
    | '/services/outdoor-maintenance'
    | '/services/rubbish-removal'
    | '/services/solar-panel-cleaning'
    | '/services/vacate-cleaning'
    | '/services/window-carpet'
    | '/services/window-cleaning'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/before-after'
    | '/blog'
    | '/contact'
    | '/services'
    | '/blog/$slug'
    | '/services/airbnb-cleaning'
    | '/services/carpet-upholstery'
    | '/services/commercial-cleaning'
    | '/services/gutter-cleaning'
    | '/services/home-cleaning'
    | '/services/house-cleaning'
    | '/services/lawn-gardening'
    | '/services/ndis-dva'
    | '/services/office-cleaning'
    | '/services/outdoor-maintenance'
    | '/services/rubbish-removal'
    | '/services/solar-panel-cleaning'
    | '/services/vacate-cleaning'
    | '/services/window-carpet'
    | '/services/window-cleaning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BeforeAfterRoute: typeof BeforeAfterRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/before-after': {
      id: '/before-after'
      path: '/before-after'
      fullPath: '/before-after'
      preLoaderRoute: typeof BeforeAfterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/window-cleaning': {
      id: '/services/window-cleaning'
      path: '/window-cleaning'
      fullPath: '/services/window-cleaning'
      preLoaderRoute: typeof ServicesWindowCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/window-carpet': {
      id: '/services/window-carpet'
      path: '/window-carpet'
      fullPath: '/services/window-carpet'
      preLoaderRoute: typeof ServicesWindowCarpetRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/vacate-cleaning': {
      id: '/services/vacate-cleaning'
      path: '/vacate-cleaning'
      fullPath: '/services/vacate-cleaning'
      preLoaderRoute: typeof ServicesVacateCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/solar-panel-cleaning': {
      id: '/services/solar-panel-cleaning'
      path: '/solar-panel-cleaning'
      fullPath: '/services/solar-panel-cleaning'
      preLoaderRoute: typeof ServicesSolarPanelCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/rubbish-removal': {
      id: '/services/rubbish-removal'
      path: '/rubbish-removal'
      fullPath: '/services/rubbish-removal'
      preLoaderRoute: typeof ServicesRubbishRemovalRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/outdoor-maintenance': {
      id: '/services/outdoor-maintenance'
      path: '/outdoor-maintenance'
      fullPath: '/services/outdoor-maintenance'
      preLoaderRoute: typeof ServicesOutdoorMaintenanceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/office-cleaning': {
      id: '/services/office-cleaning'
      path: '/office-cleaning'
      fullPath: '/services/office-cleaning'
      preLoaderRoute: typeof ServicesOfficeCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ndis-dva': {
      id: '/services/ndis-dva'
      path: '/ndis-dva'
      fullPath: '/services/ndis-dva'
      preLoaderRoute: typeof ServicesNdisDvaRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/lawn-gardening': {
      id: '/services/lawn-gardening'
      path: '/lawn-gardening'
      fullPath: '/services/lawn-gardening'
      preLoaderRoute: typeof ServicesLawnGardeningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/house-cleaning': {
      id: '/services/house-cleaning'
      path: '/house-cleaning'
      fullPath: '/services/house-cleaning'
      preLoaderRoute: typeof ServicesHouseCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/home-cleaning': {
      id: '/services/home-cleaning'
      path: '/home-cleaning'
      fullPath: '/services/home-cleaning'
      preLoaderRoute: typeof ServicesHomeCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/gutter-cleaning': {
      id: '/services/gutter-cleaning'
      path: '/gutter-cleaning'
      fullPath: '/services/gutter-cleaning'
      preLoaderRoute: typeof ServicesGutterCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/commercial-cleaning': {
      id: '/services/commercial-cleaning'
      path: '/commercial-cleaning'
      fullPath: '/services/commercial-cleaning'
      preLoaderRoute: typeof ServicesCommercialCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/carpet-upholstery': {
      id: '/services/carpet-upholstery'
      path: '/carpet-upholstery'
      fullPath: '/services/carpet-upholstery'
      preLoaderRoute: typeof ServicesCarpetUpholsteryRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/airbnb-cleaning': {
      id: '/services/airbnb-cleaning'
      path: '/airbnb-cleaning'
      fullPath: '/services/airbnb-cleaning'
      preLoaderRoute: typeof ServicesAirbnbCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesAirbnbCleaningRoute: typeof ServicesAirbnbCleaningRoute
  ServicesCarpetUpholsteryRoute: typeof ServicesCarpetUpholsteryRoute
  ServicesCommercialCleaningRoute: typeof ServicesCommercialCleaningRoute
  ServicesGutterCleaningRoute: typeof ServicesGutterCleaningRoute
  ServicesHomeCleaningRoute: typeof ServicesHomeCleaningRoute
  ServicesHouseCleaningRoute: typeof ServicesHouseCleaningRoute
  ServicesLawnGardeningRoute: typeof ServicesLawnGardeningRoute
  ServicesNdisDvaRoute: typeof ServicesNdisDvaRoute
  ServicesOfficeCleaningRoute: typeof ServicesOfficeCleaningRoute
  ServicesOutdoorMaintenanceRoute: typeof ServicesOutdoorMaintenanceRoute
  ServicesRubbishRemovalRoute: typeof ServicesRubbishRemovalRoute
  ServicesSolarPanelCleaningRoute: typeof ServicesSolarPanelCleaningRoute
  ServicesVacateCleaningRoute: typeof ServicesVacateCleaningRoute
  ServicesWindowCarpetRoute: typeof ServicesWindowCarpetRoute
  ServicesWindowCleaningRoute: typeof ServicesWindowCleaningRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAirbnbCleaningRoute: ServicesAirbnbCleaningRoute,
  ServicesCarpetUpholsteryRoute: ServicesCarpetUpholsteryRoute,
  ServicesCommercialCleaningRoute: ServicesCommercialCleaningRoute,
  ServicesGutterCleaningRoute: ServicesGutterCleaningRoute,
  ServicesHomeCleaningRoute: ServicesHomeCleaningRoute,
  ServicesHouseCleaningRoute: ServicesHouseCleaningRoute,
  ServicesLawnGardeningRoute: ServicesLawnGardeningRoute,
  ServicesNdisDvaRoute: ServicesNdisDvaRoute,
  ServicesOfficeCleaningRoute: ServicesOfficeCleaningRoute,
  ServicesOutdoorMaintenanceRoute: ServicesOutdoorMaintenanceRoute,
  ServicesRubbishRemovalRoute: ServicesRubbishRemovalRoute,
  ServicesSolarPanelCleaningRoute: ServicesSolarPanelCleaningRoute,
  ServicesVacateCleaningRoute: ServicesVacateCleaningRoute,
  ServicesWindowCarpetRoute: ServicesWindowCarpetRoute,
  ServicesWindowCleaningRoute: ServicesWindowCleaningRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BeforeAfterRoute: BeforeAfterRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
